# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_type', models.BooleanField(default=False, verbose_name='Поставщик?')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='Название компании')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Возврат товара',
                'verbose_name_plural': 'Возвраты товара',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('reason', models.CharField(max_length=500, verbose_name='Причина')),
                ('purchase_returns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.PurchaseReturn', verbose_name='Возврат товара')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Поступление товара',
                'verbose_name_plural': 'Поступления товара',
            },
        ),
        migrations.CreateModel(
            name='ReceiptContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField(verbose_name='Закуплено')),
                ('price', models.PositiveIntegerField(verbose_name='Закупочная цена')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Receipt', verbose_name='Поступление товара')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(verbose_name='Дата составления')),
                ('paid', models.BooleanField(verbose_name='Оплачено?')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка с суммы')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Реализация товара',
                'verbose_name_plural': 'Реалицазии товара',
            },
        ),
        migrations.CreateModel(
            name='SellingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Продажная цена')),
                ('retail_price', models.PositiveIntegerField(editable=False, verbose_name='Розничная цена')),
                ('complement', models.BooleanField(default=False, verbose_name='Докупка')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('selling_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Selling', verbose_name='Реализация товара')),
            ],
        ),
        migrations.AddField(
            model_name='purchasereturncontent',
            name='selling_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.SellingContent', verbose_name='selling content'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Selling', verbose_name='Реализация товара'),
        ),
    ]
