# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_turnover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingcontent',
            old_name='retail_price',
            new_name='sold_price',
        ),
        migrations.AddField(
            model_name='sellingcontent',
            name='pack',
            field=models.BooleanField(default=False, verbose_name='Коробка?'),
        ),
        migrations.AddField(
            model_name='sellingcontent',
            name='wholesale',
            field=models.BooleanField(default=False, verbose_name='Оптом?'),
        ),
        migrations.AlterField(
            model_name='receiptcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='receiptcontent',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sellingcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='sellingcontent',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Товар'),
        ),
    ]
