# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_turnover', '0002_auto_20171023_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ('first_name',), 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'verbose_name': 'Возврат', 'verbose_name_plural': 'Возвраты'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturncontent',
            options={'verbose_name': 'Позиция возврата', 'verbose_name_plural': 'Позиции возвратов'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Приход', 'verbose_name_plural': 'Приходы'},
        ),
        migrations.AlterModelOptions(
            name='receiptcontent',
            options={'verbose_name': 'Позиция прихода', 'verbose_name_plural': 'Позиции приходов'},
        ),
        migrations.AlterModelOptions(
            name='selling',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='sellingcontent',
            options={'verbose_name': 'Позиция продажи', 'verbose_name_plural': 'Позиции продаж'},
        ),
        migrations.RemoveField(
            model_name='selling',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='selling',
            name='paid',
        ),
        migrations.AddField(
            model_name='selling',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Selling', verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='purchasereturncontent',
            name='purchase_returns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.PurchaseReturn', verbose_name='Возврат'),
        ),
        migrations.AlterField(
            model_name='purchasereturncontent',
            name='selling_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.SellingContent', verbose_name='Позиция продажи'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='receiptcontent',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Receipt', verbose_name='Приход'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата составления'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='sellingcontent',
            name='selling_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_turnover.Selling', verbose_name='Продажа'),
        ),
    ]
