# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Glue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(help_text='гр', verbose_name='Вес пачки')),
                ('retail_price', models.PositiveSmallIntegerField(verbose_name='Розничная цена')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('pack', models.PositiveSmallIntegerField(verbose_name='Пачек в коробке')),
                ('area', models.PositiveSmallIntegerField(verbose_name='На площадь')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glue.Brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Клей',
                'verbose_name_plural': 'Клеи',
            },
        ),
        migrations.CreateModel(
            name='GlueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип клея')),
            ],
            options={
                'verbose_name': 'Тип клея',
                'verbose_name_plural': 'Типы клея',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='glue',
            name='glue_type',
            field=models.ManyToManyField(to='glue.GlueType', verbose_name='Тип клея'),
        ),
    ]
