# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0002_auto_20171023_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glue',
            options={'ordering': ('brand__name', 'warehouse_str'), 'verbose_name': 'Клей', 'verbose_name_plural': 'Клеи'},
        ),
        migrations.AddField(
            model_name='glue',
            name='warehouse_str',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование для склада'),
        ),
    ]
