# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_consignment', models.CharField(max_length=20, verbose_name='Партия')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество рулонов')),
                ('stillage', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Стеллаж')),
                ('cell', models.PositiveSmallIntegerField(verbose_name='Ячейка')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='VendorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
            },
        ),
        migrations.AddField(
            model_name='theconsignment',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VendorCode'),
        ),
    ]
