# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Сокращенное название')),
                ('country_of_origin', models.CharField(choices=[('BE', 'Бельгия'), ('CH', 'Китай'), ('DE', 'Германия'), ('FR', 'Франция'), ('IT', 'Италия'), ('KR', 'Корея'), ('RU', 'Россия'), ('TR', 'Турция'), ('TW', 'Тайвань'), ('UA', 'Украина')], max_length=2, verbose_name='Страна производства')),
                ('company_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Компания производитель')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='TheConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_consignment', models.CharField(blank=True, max_length=20, verbose_name='Партия')),
                ('retail_price', models.PositiveIntegerField(default=0, verbose_name='Розничная цена')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество рулонов')),
                ('stillage', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Стеллаж')),
                ('cell', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Ячейка')),
                ('showcase', models.BooleanField(default=True, verbose_name='На витрине?')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='VendorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, unique=True, verbose_name='Артикул')),
                ('wholesale_price', models.PositiveIntegerField(default=0, verbose_name='Оптовая цена')),
                ('width', models.FloatField(default=1.06, help_text='м', verbose_name='Ширина')),
                ('length', models.FloatField(default=10.05, help_text='м', verbose_name='Длина')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Снят с производства')),
                ('pack', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рулонов в коробке')),
                ('rapport', models.CharField(blank=True, default=0, help_text='см', max_length=9, verbose_name='Раппорт')),
                ('rapport_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'произвольный'), (2, 'прямой'), (3, 'со смещением'), (4, 'обратный')], default=1, null=True, verbose_name='Тип раппорта')),
                ('marking', models.CharField(blank=True, choices=[('А', 'Акриловые'), ('Б', 'Бумажные'), ('ВВ', 'Вспененный винил'), ('ПВ', 'Плоский винил'), ('РВ', 'Рельефный винил'), ('СТЛ', 'Стеклообои'), ('СТР', 'Структурные'), ('ТСК', 'Текстильные')], max_length=3, verbose_name='Маркировка')),
                ('basis_material', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'бумага'), (2, 'флизелин')], default=2, null=True, verbose_name='Материал основы')),
                ('covering_material', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'бумага'), (2, 'винил')], default=2, null=True, verbose_name='Материал покрытия')),
                ('moisture_resistance', models.CharField(blank=True, choices=[('В-0', 'Влагостойкие при наклеивании'), ('В-1', 'Влагостойкие при эксплуатации'), ('М-1', 'Устойчивые к мытью (моющиеся)'), ('М-2', 'Высокоустойчивые к мытью'), ('М-3', 'Устойчивые к трению'), ('М-4', 'Высокоустойчивые к трению')], default='М-2', max_length=3, null=True, verbose_name='Влагостойкость')),
                ('resistance_to_light', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'средняя'), (4, 'удовлетворительная'), (5, 'хорошая'), (6, 'очень хорошая'), (7, 'отличная')], default=5, null=True, verbose_name='Светостойкость')),
                ('gluing', models.CharField(blank=True, choices=[('БК', 'Клей наносится на обои'), ('ОК', 'Клей наносится на основу'), ('ГК', 'Полотно наклеиваемые горизонтально'), ('Г', 'Гуммированные обои')], default='ОК', max_length=2, verbose_name='Наклеивание')),
                ('removal', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Снимаемые без остатка'), (2, 'Расслаиваемые'), (3, 'Увлажняемые для снятия')], default=1, null=True, verbose_name='Снятие со стены')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Brand')),
                ('combination', models.ManyToManyField(blank=True, related_name='_vendorcode_combination_+', to='main.VendorCode', verbose_name='Компаньоны')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
            },
        ),
        migrations.AddField(
            model_name='theconsignment',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VendorCode', verbose_name='Артикул'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('name', 'country_of_origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='theconsignment',
            unique_together=set([('vendor_code', 'the_consignment')]),
        ),
    ]
