# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcode',
            name='vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
