# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170816_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theconsignment',
            name='cell',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ячейка'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='stillage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=4, null=True, verbose_name='Стеллаж'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VendorCode', verbose_name='Артикул'),
        ),
    ]
