# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170816_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcode',
            name='length',
            field=models.FloatField(default=10, verbose_name='Длина (м)'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='width',
            field=models.FloatField(default=1.06, verbose_name='Ширина (м)'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='stillage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=7, null=True, verbose_name='Стеллаж'),
        ),
    ]
