# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170816_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theconsignment',
            name='cell',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True, verbose_name='Ячейка'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='stillage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, null=True, verbose_name='Стеллаж'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='the_consignment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Партия'),
        ),
    ]
