# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170817_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='theconsignment',
            name='showcase',
            field=models.BooleanField(verbose_name='На витрине?'),
        ),
    ]
