# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170821_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_type', models.BooleanField(default=False, verbose_name='Поставщик?')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Возврат товара',
                'verbose_name_plural': 'Возвраты товара',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('purchase_returns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PurchaseReturns')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contractor')),
            ],
            options={
                'verbose_name': 'Поступление товара',
                'verbose_name_plural': 'Поступления товара',
            },
        ),
        migrations.CreateModel(
            name='ReceiptContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.PositiveSmallIntegerField(verbose_name='Закуплено')),
                ('balance', models.PositiveSmallIntegerField(editable=False, verbose_name='Остаток')),
                ('price', models.PositiveIntegerField(verbose_name='Закупочная цена')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(verbose_name='Дата составления')),
                ('paid', models.BooleanField(verbose_name='Оплачено?')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contractor')),
            ],
            options={
                'verbose_name': 'Реализация товара',
                'verbose_name_plural': 'Реалицазии товара',
            },
        ),
        migrations.CreateModel(
            name='SellingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Розничная цена')),
                ('retail_price', models.PositiveIntegerField(editable=False, verbose_name='Розничная цена')),
                ('selling_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Selling')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='company_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания производитель'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(choices=[('BE', 'Бельгия'), ('CH', 'Китай'), ('DE', 'Германия'), ('FR', 'Франция'), ('IT', 'Италия'), ('KR', 'Корея'), ('RU', 'Россия'), ('TR', 'Турция'), ('TW', 'Тайвань'), ('UA', 'Украина')], default='RU', max_length=2, verbose_name='Страна производства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='basis_material',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'бумага'), (2, 'флизелин')], default=2, null=True, verbose_name='Материал основы'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='combination',
            field=models.ManyToManyField(blank=True, related_name='_vendorcode_combination_+', to='main.VendorCode', verbose_name='Комбинации'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='covering_material',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'бумага'), (2, 'винил')], default=2, null=True, verbose_name='Материал покрытия'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='discontinued',
            field=models.BooleanField(default=False, verbose_name='Снят с производства'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='gluing',
            field=models.CharField(blank=True, choices=[('БК', 'Клей наносится на обои'), ('ОК', 'Клей наносится на основу'), ('ГК', 'Полотно наклеиваемые горизонтально'), ('Г', 'Гуммированные обои')], default='ОК', max_length=2, null=True, verbose_name='Наклеивание'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='marking',
            field=models.CharField(blank=True, choices=[('А', 'Акриловые'), ('Б', 'Бумажные'), ('ВВ', 'Вспененный винил'), ('ПВ', 'Плоский винил'), ('РВ', 'Рельефный винил'), ('СТЛ', 'Стеклообои'), ('СТР', 'Структурные'), ('ТСК', 'Текстильные')], max_length=3, null=True, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='moisture_resistance',
            field=models.CharField(blank=True, choices=[('В-0', 'Влагостойкие при наклеивании'), ('В-1', 'Влагостойкие при эксплуатации'), ('М-1', 'Устойчивые к мытью (моющиеся)'), ('М-2', 'Высокоустойчивые к мытью'), ('М-3', 'Устойчивые к трению'), ('М-4', 'Высокоустойчивые к трению')], default='М-2', max_length=3, null=True, verbose_name='Влагостойкость'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='pack',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рулонов в упаковке'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='rapport',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='см', null=True, verbose_name='Раппорт'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='rapport_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'произвольный'), (2, 'прямой'), (3, 'со смещением'), (4, 'обратный')], default=1, null=True, verbose_name='Тип раппорта'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='removal',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Снимаемые без остатка'), (2, 'Расслаиваемые'), (3, 'Увлажняемые для снятия')], default=1, null=True, verbose_name='Снятие со стены'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='resistance_to_light',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'средняя'), (4, 'удовлетворительная'), (5, 'хорошая'), (6, 'очень хорошая'), (7, 'отличная')], default=5, null=True, verbose_name='Светостойкость'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='retail_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Розничная цена'),
        ),
        migrations.AddField(
            model_name='vendorcode',
            name='wholesale_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='showcase',
            field=models.BooleanField(default=True, verbose_name='На витрине?'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='length',
            field=models.FloatField(default=10, help_text='м', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='width',
            field=models.FloatField(default=1.06, help_text='м', verbose_name='Ширина'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('name', 'country_of_origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='theconsignment',
            unique_together=set([('vendor_code', 'the_consignment')]),
        ),
        migrations.AddField(
            model_name='sellingcontent',
            name='the_consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TheConsignment'),
        ),
        migrations.AddField(
            model_name='receiptcontent',
            name='the_consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TheConsignment'),
        ),
        migrations.AddField(
            model_name='purchasereturnscontent',
            name='selling_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SellingContent'),
        ),
        migrations.AddField(
            model_name='purchasereturns',
            name='selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Selling'),
        ),
    ]
