# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170914_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='theconsignment',
            name='retail_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='combination',
            field=models.ManyToManyField(blank=True, related_name='_vendorcode_combination_+', to='main.VendorCode', verbose_name='Компаньоны'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='length',
            field=models.FloatField(default=10.05, help_text='м', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='rapport',
            field=models.CharField(blank=True, default=0, help_text='см', max_length=9, verbose_name='Раппорт'),
        ),
    ]
