# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170922_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcode',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='purchasereturnscontent',
            name='reason',
            field=models.CharField(default='', max_length=500, verbose_name='Причина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_of_origin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Компания производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellingcontent',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Продажная цена'),
        ),
        migrations.AlterField(
            model_name='theconsignment',
            name='the_consignment',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Партия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='gluing',
            field=models.CharField(blank=True, choices=[('БК', 'Клей наносится на обои'), ('ОК', 'Клей наносится на основу'), ('ГК', 'Полотно наклеиваемые горизонтально'), ('Г', 'Гуммированные обои')], default='ОК', max_length=2, verbose_name='Наклеивание'),
        ),
        migrations.AlterField(
            model_name='vendorcode',
            name='marking',
            field=models.CharField(blank=True, choices=[('А', 'Акриловые'), ('Б', 'Бумажные'), ('ВВ', 'Вспененный винил'), ('ПВ', 'Плоский винил'), ('РВ', 'Рельефный винил'), ('СТЛ', 'Стеклообои'), ('СТР', 'Структурные'), ('ТСК', 'Текстильные')], default='', max_length=3, verbose_name='Маркировка'),
            preserve_default=False,
        ),
    ]
