# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Тула (эконом)'), (2, 'Тула (VIP)'), (3, 'Басс (люкс)'), (4, 'Басс (премиум)')], verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('vendor_code', models.CharField(blank=True, max_length=10, verbose_name='Артикул')),
                ('sheet', models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (6, 6), (8, 8), (9, 9), (12, 12), (16, 16)], verbose_name='Листов')),
                ('width', models.PositiveSmallIntegerField(choices=[(97, 97), (98, 98), (134, 134), (136, 136), (194, 194), (196, 196), (200, 200), (201, 201), (204, 204), (260, 260), (261, 261), (268, 268), (272, 272), (291, 291), (294, 294), (300, 300), (388, 388), (392, 392), (408, 408)], verbose_name='Ширина')),
                ('height', models.PositiveSmallIntegerField(choices=[(97, 97), (98, 98), (134, 134), (136, 136), (194, 194), (196, 196), (200, 200), (201, 201), (204, 204), (260, 260), (261, 261), (268, 268), (272, 272), (291, 291), (294, 294), (300, 300), (388, 388), (392, 392), (408, 408)], verbose_name='Высота')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('retail_price', models.PositiveIntegerField(verbose_name='Розничная цена')),
            ],
            options={
                'verbose_name': 'Фотообои',
                'verbose_name_plural': 'Фотообои',
            },
        ),
    ]
